# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Admin/Documents/SimpleEM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/Admin/Documents/SimpleEM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Admin/Documents/SimpleEM/CMakeFiles /mnt/c/Users/Admin/Documents/SimpleEM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/Admin/Documents/SimpleEM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tinyem

# Build rule for target.
tinyem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tinyem
.PHONY : tinyem

# fast build rule for target.
tinyem/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyem.dir/build.make CMakeFiles/tinyem.dir/build
.PHONY : tinyem/fast

#=============================================================================
# Target rules for targets named dummy

# Build rule for target.
dummy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dummy
.PHONY : dummy

# fast build rule for target.
dummy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy.dir/build.make CMakeFiles/dummy.dir/build
.PHONY : dummy/fast

#=============================================================================
# Target rules for targets named tcp_server

# Build rule for target.
tcp_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tcp_server
.PHONY : tcp_server

# fast build rule for target.
tcp_server/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/build
.PHONY : tcp_server/fast

#=============================================================================
# Target rules for targets named tcp_client

# Build rule for target.
tcp_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tcp_client
.PHONY : tcp_client

# fast build rule for target.
tcp_client/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/build
.PHONY : tcp_client/fast

examples/dummy/src/dummy.o: examples/dummy/src/dummy.cpp.o
.PHONY : examples/dummy/src/dummy.o

# target to build an object file
examples/dummy/src/dummy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy.dir/build.make CMakeFiles/dummy.dir/examples/dummy/src/dummy.cpp.o
.PHONY : examples/dummy/src/dummy.cpp.o

examples/dummy/src/dummy.i: examples/dummy/src/dummy.cpp.i
.PHONY : examples/dummy/src/dummy.i

# target to preprocess a source file
examples/dummy/src/dummy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy.dir/build.make CMakeFiles/dummy.dir/examples/dummy/src/dummy.cpp.i
.PHONY : examples/dummy/src/dummy.cpp.i

examples/dummy/src/dummy.s: examples/dummy/src/dummy.cpp.s
.PHONY : examples/dummy/src/dummy.s

# target to generate assembly for a file
examples/dummy/src/dummy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy.dir/build.make CMakeFiles/dummy.dir/examples/dummy/src/dummy.cpp.s
.PHONY : examples/dummy/src/dummy.cpp.s

src/src/proc_frame.o: src/src/proc_frame.cpp.o
.PHONY : src/src/proc_frame.o

# target to build an object file
src/src/proc_frame.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyem.dir/build.make CMakeFiles/tinyem.dir/src/src/proc_frame.cpp.o
.PHONY : src/src/proc_frame.cpp.o

src/src/proc_frame.i: src/src/proc_frame.cpp.i
.PHONY : src/src/proc_frame.i

# target to preprocess a source file
src/src/proc_frame.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyem.dir/build.make CMakeFiles/tinyem.dir/src/src/proc_frame.cpp.i
.PHONY : src/src/proc_frame.cpp.i

src/src/proc_frame.s: src/src/proc_frame.cpp.s
.PHONY : src/src/proc_frame.s

# target to generate assembly for a file
src/src/proc_frame.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyem.dir/build.make CMakeFiles/tinyem.dir/src/src/proc_frame.cpp.s
.PHONY : src/src/proc_frame.cpp.s

src/src/tcp_client.o: src/src/tcp_client.cpp.o
.PHONY : src/src/tcp_client.o

# target to build an object file
src/src/tcp_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/src/src/tcp_client.cpp.o
.PHONY : src/src/tcp_client.cpp.o

src/src/tcp_client.i: src/src/tcp_client.cpp.i
.PHONY : src/src/tcp_client.i

# target to preprocess a source file
src/src/tcp_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/src/src/tcp_client.cpp.i
.PHONY : src/src/tcp_client.cpp.i

src/src/tcp_client.s: src/src/tcp_client.cpp.s
.PHONY : src/src/tcp_client.s

# target to generate assembly for a file
src/src/tcp_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_client.dir/build.make CMakeFiles/tcp_client.dir/src/src/tcp_client.cpp.s
.PHONY : src/src/tcp_client.cpp.s

src/src/tcp_server.o: src/src/tcp_server.cpp.o
.PHONY : src/src/tcp_server.o

# target to build an object file
src/src/tcp_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/src/tcp_server.cpp.o
.PHONY : src/src/tcp_server.cpp.o

src/src/tcp_server.i: src/src/tcp_server.cpp.i
.PHONY : src/src/tcp_server.i

# target to preprocess a source file
src/src/tcp_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/src/tcp_server.cpp.i
.PHONY : src/src/tcp_server.cpp.i

src/src/tcp_server.s: src/src/tcp_server.cpp.s
.PHONY : src/src/tcp_server.s

# target to generate assembly for a file
src/src/tcp_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_server.dir/build.make CMakeFiles/tcp_server.dir/src/src/tcp_server.cpp.s
.PHONY : src/src/tcp_server.cpp.s

src/src/time.o: src/src/time.cpp.o
.PHONY : src/src/time.o

# target to build an object file
src/src/time.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyem.dir/build.make CMakeFiles/tinyem.dir/src/src/time.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy.dir/build.make CMakeFiles/dummy.dir/src/src/time.cpp.o
.PHONY : src/src/time.cpp.o

src/src/time.i: src/src/time.cpp.i
.PHONY : src/src/time.i

# target to preprocess a source file
src/src/time.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyem.dir/build.make CMakeFiles/tinyem.dir/src/src/time.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy.dir/build.make CMakeFiles/dummy.dir/src/src/time.cpp.i
.PHONY : src/src/time.cpp.i

src/src/time.s: src/src/time.cpp.s
.PHONY : src/src/time.s

# target to generate assembly for a file
src/src/time.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyem.dir/build.make CMakeFiles/tinyem.dir/src/src/time.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dummy.dir/build.make CMakeFiles/dummy.dir/src/src/time.cpp.s
.PHONY : src/src/time.cpp.s

src/src/tinyem.o: src/src/tinyem.cpp.o
.PHONY : src/src/tinyem.o

# target to build an object file
src/src/tinyem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyem.dir/build.make CMakeFiles/tinyem.dir/src/src/tinyem.cpp.o
.PHONY : src/src/tinyem.cpp.o

src/src/tinyem.i: src/src/tinyem.cpp.i
.PHONY : src/src/tinyem.i

# target to preprocess a source file
src/src/tinyem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyem.dir/build.make CMakeFiles/tinyem.dir/src/src/tinyem.cpp.i
.PHONY : src/src/tinyem.cpp.i

src/src/tinyem.s: src/src/tinyem.cpp.s
.PHONY : src/src/tinyem.s

# target to generate assembly for a file
src/src/tinyem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tinyem.dir/build.make CMakeFiles/tinyem.dir/src/src/tinyem.cpp.s
.PHONY : src/src/tinyem.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dummy"
	@echo "... tcp_client"
	@echo "... tcp_server"
	@echo "... tinyem"
	@echo "... examples/dummy/src/dummy.o"
	@echo "... examples/dummy/src/dummy.i"
	@echo "... examples/dummy/src/dummy.s"
	@echo "... src/src/proc_frame.o"
	@echo "... src/src/proc_frame.i"
	@echo "... src/src/proc_frame.s"
	@echo "... src/src/tcp_client.o"
	@echo "... src/src/tcp_client.i"
	@echo "... src/src/tcp_client.s"
	@echo "... src/src/tcp_server.o"
	@echo "... src/src/tcp_server.i"
	@echo "... src/src/tcp_server.s"
	@echo "... src/src/time.o"
	@echo "... src/src/time.i"
	@echo "... src/src/time.s"
	@echo "... src/src/tinyem.o"
	@echo "... src/src/tinyem.i"
	@echo "... src/src/tinyem.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

